### ISSUE TITLE
[Migration][Test] jUnit4 -> jUnit5 UT cases migration

### ISSUE THREAD

**Issue by EricGao888** [apache/dolphinscheduler#12301]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

* This is part of DSIP-10 #10573

* By this moment, we have added jUnit 5 dependencies #11332 and removed all `Powermock` related code #11405. It is high time that we migrate all the UT cases from jUnit 4 to jUnit 5 and remove the dependency of `junit-vintage-engine` so that there will be one and only one version of unit test cases, which is jUnit5, in the whole project.

### SOP

These two following articles are recommended for you to understand the whole process. In order to keep the instructions brief and concise, I summarize some key points of these two articles as well as add a few extra operations based on practice for your reference:

* https://blogs.oracle.com/javamagazine/post/migrating-from-junit-4-to-junit-5-important-differences-and-benefits
* https://blog.jetbrains.com/idea/2020/08/migrating-from-junit-4-to-junit-5/

BTW, I suggest you perform this SOP below by module or by file, instead of doing it for the whole project. This helps you increase efficiency. 

1. Perform basic migration through `Intellij IDE` for the module you choose. 
![screenshot1](https://user-images.githubusercontent.com/34905992/194875626-6560812b-c776-4601-9425-4eafea3288bb.png)
2. Replace `@RunWith(MockitoJUnitRunner.class)` with `@ExtendWith(MockitoExtension.class)` if necessary.
3. Replace `Assert` with `Assertions`.
4. Fix expected exception if necessary.

```java
// jUnit 4
@Test(expected = Exception.class)
public void testThrowsException() throws Exception {
    // ...
}

// jUnit 5
@Test
public void testThrowsException() throws Exception {
    Assertions.assertThrows(Exception.class, () -> {
        //...
    });
}
```

6. Fix timeout if necessary. 

```java
// jUnit 4
@Test(timeout = 10)
public void testFailWithTimeout() throws InterruptedException {
    Thread.sleep(100);
}

// jUnit 5
@Test
void testFailWithTimeout() throws InterruptedException {
    Assertions.assertTimeout(Duration.ofMillis(10), () -> Thread.sleep(100));
}

Assertions.assertTimeout(Duration.ofMillis(60000), () -> {});
```

8. Replace `@Ignore` with `@Disable` if necessary.
9. Replace `org.junit.rules.TemporaryFolder` with `org.junit.jupiter.api.io.TempDir` and use `@TempDir` if necessary.
10. Run the UT file you changed to see whether all cases pass successfully. 
11. Fix unnecessary stubbings if necessary. This is caused by changing `@Before` into `@BeforeEach`. The recommend method is to use `@MockitoSettings(strictness = Strictness.LENIENT)`. Alternatively, you could either remove the unnecessary stubbings from  `@BeforeEach` and only put them where they needed or use `Mockito.lenient().when(......` for `Mockito.when(......` to bypass the `stubbing  check`.
12. Global search in your module and make sure all `org.junit.xxxx` has been migrated to `org.junit.jupiter.api.xxx`

### PR Example
* #12299

### Sub-Tasks

We hope to complete all the following sub-tasks ***before Oct. 25th*** because DSIP-10 depends on this issue and all UT cases are supposed to be migrated to jUnit 5 before the start of UT refactoring.

- [x] Migrate all UT cases from jUnit 4 to jUnit 5 in `task-plugin` module: #12299
- [x] Migrate all UT cases from jUnit 4 to jUnit 5 in `alert` and `api` module: #12313
- [x] Migrate all UT cases from jUnit 4 to jUnit 5 in `dao` module: #12319 
- [x] Migrate all UT cases from jUnit 4 to jUnit 5 in `data-quality`, `datasource-plugin` and `registry` module: #12322
- [x] Migrate all UT cases from jUnit 4 to jUnit 5 in `master`, `worker` and `remote` module: #12316 
- [x] Migrate all UT cases from jUnit 4 to jUnit 5 in `common`, `service` and `spi` module: #12317 
- [x] Migrate all UT cases from jUnit 4 to jUnit 5 in `microbench` and `e2e` module: #12333
- [x] Block explicit imports of jUnit 4 library. #12395

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by DarkAssassinator** [comment]
hi @EricGao888 may i can help to `jUnit4 -> jUnit5 UT cases migration`. any module is ok

**Comment by EricGao888** [comment]
> hi @EricGao888 may i can help to `jUnit4 -> jUnit5 UT cases migration`. any module is ok

Great! Thanks for the help. Currently I'm estimating the workload. I will divide this issue into sub-tasks by Wednesday. And you are free to choose any sub-task you like to help with this issue at that time : )

**Comment by DarkAssassinator** [comment]
I can do `master` `worker` `remote` `common` `service` `spi`, and i can take this opportunity to familiarize myself with the source code again

**Comment by EricGao888** [comment]
> I can do `master` `worker` `remote` `common` `service` `spi`, and i can take this opportunity to familiarize myself with the source code again

@DarkAssassinator Sure, feel free! Could u please create two issues and post the links in the comment? I will link them to the `sub-tasks` section. Thx.

**Comment by fuchanghai** [comment]
hi @EricGao888 may i can help to  ``` jUnit4 -> jUnit5 UT cases migration ```

**Comment by EricGao888** [comment]
> hi @EricGao888 may i can help to `jUnit4 -> jUnit5 UT cases migration`

@fuchanghai Sure, would u like to pick the `dao` module?

**Comment by fuchanghai** [comment]
> > hi @EricGao888 may i can help to `jUnit4 -> jUnit5 UT cases migration`
> 
> @fuchanghai Sure, would u like to pick the `dao` module?

yes

**Comment by DarkAssassinator** [comment]
> 



> > hi @EricGao888 may i can help to `jUnit4 -> jUnit5 UT cases migration`. any module is ok
> 
> Great! Thanks for the help. Currently I'm estimating the workload. I will divide this issue into sub-tasks by Wednesday. And you are free to choose any sub-task you like to help with this issue at that time : )

@EricGao888 Sure, please check the following issues:
+ [x] Migrate all UT cases from jUnit 4 to jUnit 5 in master, worker and remote module : #12316 
+ [x] Migrate all UT cases from jUnit 4 to jUnit 5 in common, service and spi module:  #12317

**Comment by EricGao888** [comment]
> > 
> 
> > > hi @EricGao888 may i can help to `jUnit4 -> jUnit5 UT cases migration`. any module is ok
> > 
> > 
> > Great! Thanks for the help. Currently I'm estimating the workload. I will divide this issue into sub-tasks by Wednesday. And you are free to choose any sub-task you like to help with this issue at that time : )
> 
> @EricGao888 Sure, please check the following issues:
> 
> * [x]  Migrate all UT cases from jUnit 4 to jUnit 5 in master, worker and remote module : [[Migration][Test] Migrate all UT cases from jUnit 4 to jUnit 5 in master, worker and remote module #12316](https://github.com/apache/dolphinscheduler/issues/12316)
> * [x]  Migrate all UT cases from jUnit 4 to jUnit 5 in common, service and spi module:  [[Migrate ][Test] Migrate all UT cases from jUnit 4 to jUnit 5 in common, service and spi module #12317](https://github.com/apache/dolphinscheduler/issues/12317)

Thanks, I've linked them in the sub-tasks above.

**Comment by fuchanghai** [comment]
@EricGao888 plz check the issue #12319

**Comment by EricGao888** [comment]
> @EricGao888 plz check the issue #12319

@fuchanghai done, thx

**Comment by rickchengx** [comment]
Hi, @EricGao888 I want to try microbench and e2e.
* Here is the issue #12333

**Comment by EricGao888** [comment]
> Hi, @EricGao888 I want to try microbench and e2e.
> 
> * Here is the issue [[Migration][Test] Migrate all UT cases from jUnit 4 to jUnit 5 in microbench and e2e module #12333](https://github.com/apache/dolphinscheduler/issues/12333)

Sure, thx.
