### ISSUE TITLE
[Improvement][Service] Refactor ProcessServiceImpl in service module.

### ISSUE THREAD

**Issue by DarkAssassinator** [apache/dolphinscheduler#12403]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

**Why need refactor `ProcessServiceImpl`?**
The number of lines of code in `ProcessServiceImpl` exceed 3K+ lines,
+ This will bring great challenges to post-maintenance work.
+ Also it's a very bad experience for the reader.
+ Corresponding unit tests are more difficult to cover.

### Sub-Task
Becasue this class contain 110+ interface methods and 3k+ code lines. If the modification range of a single task is relatively large, so i decomposed it into the following sub-tasks to improve the efficiency of review and merge, while ensuring the scope of influence. Refator should keep small steps. 

- [x] Migrate all command-related interface functions from ProcessServiceImpl. #12468
- [x] Migrate all taskInstance-related interface functions from ProcessServiceImpl #12469
- [x] Migrate all workergroup-related interface functions from ProcessServiceImpl #12470
- [ ] Migrate all dqrule-related interface functions from ProcessServiceImpl #12471
- [ ] Migrate all user-related and tenant-related interface functions from ProcessServiceImpl #12472
- [ ] Migrate all udf-related interface functions from ProcessServiceImpl  #11228
- [ ] Migrate all other other interface functions not related to Workflow from ProcessServiceImpl #12473

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fuchanghai** [comment]
@DarkAssassinator can you relation #11228

**Comment by DarkAssassinator** [comment]
because the scope of this part of the refactoring is relatively large, so I split it into multiple sub-tasks, in order to control the scope of influence and facilitate review and merge. cc @EricGao888 @songjianet

**Comment by EricGao888** [comment]
> because the scope of this part of the refactoring is relatively large, so I split it into multiple sub-tasks, in order to control the scope of influence and facilitate review and merge. cc @EricGao888 @songjianet

@DarkAssassinator I'm +1 to the refactoring of `ProcessServiceImpl `.  But `ProcessServiceImpl` is in one of the core modules, I think we should add related unit tests during the refactoring instead of after the refactoring.

BTW, may I ask whether you want to do all of these by yourself or need some more hands?

**Comment by DarkAssassinator** [comment]
> > because the scope of this part of the refactoring is relatively large, so I split it into multiple sub-tasks, in order to control the scope of influence and facilitate review and merge. cc @EricGao888 @songjianet
> 
> @DarkAssassinator I'm +1 to the refactoring of `ProcessServiceImpl `. But `ProcessServiceImpl` is in one of the core modules, I think we should add related unit tests during the refactoring instead of after the refactoring.
> 
> BTW, may I ask whether you want to do all of these by yourself or need some more hands?

Sure, one of the purposes of refactoring it is that the current test rate coverage is not enough.
need some more hands? -> Sure, @fuchanghai will help me to refactor it, and welcome more hands to join in. And I plan to focus on refactoring this part for a while. If it is delayed for too long, it may cost more work later.

**Comment by ruanwenjun** [comment]
+1, In fact, most of our logic is validate -> transform -> insert/update, we can use different sub class to to sub work.
Please start with a small service e.g. WorkerGroupService.

**Comment by DarkAssassinator** [comment]
> +1, In fact, most of our logic is validate -> transform -> insert/update, we can use different sub class to to sub work. Please start with a small service e.g. WorkerGroupService.

big +1 I just found that there are too many services included in this class, we will migrate these other services to other small services.

**Comment by fuchanghai** [comment]
> > > because the scope of this part of the refactoring is relatively large, so I split it into multiple sub-tasks, in order to control the scope of influence and facilitate review and merge. cc @EricGao888 @songjianet
> > 
> > 
> > @DarkAssassinator I'm +1 to the refactoring of `ProcessServiceImpl `. But `ProcessServiceImpl` is in one of the core modules, I think we should add related unit tests during the refactoring instead of after the refactoring.
> > BTW, may I ask whether you want to do all of these by yourself or need some more hands?
> 
> Sure, one of the purposes of refactoring it is that the current test rate coverage is not enough. need some more hands? -> Sure, @fuchanghai will help me to refactor it, and welcome more hands to join in. And I plan to focus on refactoring this part for a while. If it is delayed for too long, it may cost more work later.

> 
i'm happy to do it
