### ISSUE TITLE
[RoadMap][Year 2024] Community RoadMap

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#13459]
* For some topics which need further discussions, we temporarily note the owner as `Community`.

###  RoadMap 2024

* User Friendly
  * [x] Audit log improvement design #15423
  * [ ] [TriggerPlugin] Introduce Trigger Plugin #15330
* New Important Task or Task Related
  * [x] Dynamic Task Plugin #12526
  * [ ] Independent Release of Task Plugin
  * [x] Support Streaming Task #11352
  * [x] Task #11652 
  * [ ] Lifecycle method to TaskPlugin #14877
  * [ ] Unify the task spi about logic task and worker task #14823
* Test Improvement
  * [x] API Test #10411
  * [ ] UT Improvement #10573
* Data Ops
  * [ ] Git Ops Support
  * [ ] Git CICD related

**Comment by zhongjiajie** [comment]
Y2022Q4 roadmap in https://github.com/apache/dolphinscheduler/issues/12436

**Comment by rickchengx** [comment]
Hi, @zhongjiajie , Here are the features I'd like to implement in Y2023Q1 :)
1. [Feature] Remote Logging on more targets (Google Cloud Storage, S3, Azure Blob Storage, Etc.)
* #13017 
2. [Feature] Extending the Storage Backend for Resource Center (Google Cloud Storage, Azure Blob Storage)
* #13481 
* #13428

**Comment by davidzollo** [comment]
if you'd like to contribute any feature to the Apache DolphinScheduler, please leave a message.

**Comment by EricGao888** [comment]
> This issue has been automatically marked as stale because it has not had recent activity for 30 days. It will be closed in next 7 days if no further activity occurs.

No stale.

**Comment by EricGao888** [comment]
> This issue has been automatically marked as stale because it has not had recent activity for 30 days. It will be closed in next 7 days if no further activity occurs.

no stale

**Comment by zhongjiajie** [comment]
## Summary Roadmap Finish in 2023

* Cloud Native
  * [x] Remote Logging #13017
  * [x] K8S Operator https://github.com/apache/dolphinscheduler-operator
* New Important Task or Task related
  * Remote Task
    * [x] #13794
  * [x] Dynamic Worklfows Generate #14125

**Comment by gzusgw** [comment]
> * For some topics which need further discussions, we temporarily note the owner as `Community`.
> 
> ### RoadMap 2024
> * Cloud Native
>   
>   * [ ]  K8S Executor [[Feature][Executor] Add K8S Executor for task dispatching #13316](https://github.com/apache/dolphinscheduler/issues/13316)
> * User Friendly
>   
>   * [ ]  Dynamic Task Plugin [DSIP-20: Basic version of the dynamic task component (only implements a required field in a Shell component). #12526](https://github.com/apache/dolphinscheduler/issues/12526)
>   * [ ]  Task Parameters Sharing Optimization
>   * [ ]  Independent Release of Task Plugin
>   * [ ]  Audit log improvement design [[Improvement][Audit log] Audit log improvement design #15423](https://github.com/apache/dolphinscheduler/issues/15423)
> * New Important Task or Task Related
>   
>   * [ ]  Support Streaming Task [[DSIP-16][Task] Support stream task #11352](https://github.com/apache/dolphinscheduler/issues/11352)
>   * Remote Task
>     
>     * [ ]  [[Feature] DS can support task running on remote host, not just worker server. #11652](https://github.com/apache/dolphinscheduler/issues/11652)
>   * [ ]  [TriggerPlugin] Introduce Trigger Plugin [[DSIP-22][TriggerPlugin] Introduce Trigger Plugin #15330](https://github.com/apache/dolphinscheduler/issues/15330)
>   * [ ]  Task Sharing Storage
>   * [ ]  Trigger Workflow by Event
>   * [ ]  Lifecycle method to TaskPlugin [[DSIP-23][TaskPlugin] Add Lifecycle method to TaskPlugin  #14877](https://github.com/apache/dolphinscheduler/issues/14877)
>   * [ ]  Unify the task spi about logic task and worker task [[DSIP-21][TaskPlugin] Unify the task spi about logic task and worker task  #14823](https://github.com/apache/dolphinscheduler/issues/14823)
> * Test Improvement
>   
>   * [ ]  API Test
>   * [ ]  UT Improvement [[DSIP-10][Unit Tests] Improve DolphinScheduler unit tests #10573](https://github.com/apache/dolphinscheduler/issues/10573)
>   * [ ]  [[DSIP-22][TriggerPlugin] Introduce Trigger Plugin #15330](https://github.com/apache/dolphinscheduler/issues/15330)
> * Data Ops
>   
>   * [ ]  Git Ops Support
>   * [ ]  Git CICD related

could add loop task？ https://github.com/apache/dolphinscheduler/issues/14619

**Comment by zhongjiajie** [comment]
> > * For some topics which need further discussions, we temporarily note the owner as `Community`.
> > 
> > ### RoadMap 2024
> > 
> > * Cloud Native
> >   
> >   * [ ]   K8S Executor [[Feature][Executor] Add K8S Executor for task dispatching #13316](https://github.com/apache/dolphinscheduler/issues/13316)
> > * User Friendly
> >   
> >   * [ ]   Dynamic Task Plugin [DSIP-20: Basic version of the dynamic task component (only implements a required field in a Shell component). #12526](https://github.com/apache/dolphinscheduler/issues/12526)
> >   * [ ]   Task Parameters Sharing Optimization
> >   * [ ]   Independent Release of Task Plugin
> >   * [ ]   Audit log improvement design [[Improvement][Audit log] Audit log improvement design #15423](https://github.com/apache/dolphinscheduler/issues/15423)
> > * New Important Task or Task Related
> >   
> >   * [ ]   Support Streaming Task [[DSIP-16][Task] Support stream task #11352](https://github.com/apache/dolphinscheduler/issues/11352)
> >   * Remote Task
> >     
> >     * [ ]   [[Feature] DS can support task running on remote host, not just worker server. #11652](https://github.com/apache/dolphinscheduler/issues/11652)
> >   * [ ]   [TriggerPlugin] Introduce Trigger Plugin [[DSIP-22][TriggerPlugin] Introduce Trigger Plugin #15330](https://github.com/apache/dolphinscheduler/issues/15330)
> >   * [ ]   Task Sharing Storage
> >   * [ ]   Trigger Workflow by Event
> >   * [ ]   Lifecycle method to TaskPlugin [[DSIP-23][TaskPlugin] Add Lifecycle method to TaskPlugin  #14877](https://github.com/apache/dolphinscheduler/issues/14877)
> >   * [ ]   Unify the task spi about logic task and worker task [[DSIP-21][TaskPlugin] Unify the task spi about logic task and worker task  #14823](https://github.com/apache/dolphinscheduler/issues/14823)
> > * Test Improvement
> >   
> >   * [ ]   API Test
> >   * [ ]   UT Improvement [[DSIP-10][Unit Tests] Improve DolphinScheduler unit tests #10573](https://github.com/apache/dolphinscheduler/issues/10573)
> >   * [ ]   [[DSIP-22][TriggerPlugin] Introduce Trigger Plugin #15330](https://github.com/apache/dolphinscheduler/issues/15330)
> > * Data Ops
> >   
> >   * [ ]   Git Ops Support
> >   * [ ]   Git CICD related
> 
> could add loop task？ #14619

not sure whether is like dynamic task, so I add some comment on it, which you can see in https://github.com/apache/dolphinscheduler/issues/14619#issuecomment-1925563753

**Comment by Dyqer** [comment]
Hi, Team, How about to create a Java SDK?

**Comment by lenboo** [comment]
put it back 
* Cloud Native
  * [ ] K8S Executor #13316
