### ISSUE TITLE
[Version Check List] Version 3.2.0 release checklist and help wanted

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#14372]
# Aims 

We plan release version 3.2.0 in Jul 2023 or Aug 2023, but due to 3.2.0 have huge of features add and refactor. we need some help before we release it.

This checklist separate into three parts:
* Major functionality in dolphinscheduler like project, workflow, task create and run. **The highest priority**.
* Refactor functionality exists in version 3.1.x like resource center, datasource. **High priority**
* New functionality in 3.2.0. **Medium priority**

# Who Can join?

Anyone we can join us to test the prepare version

# How to check

You need to get the source code from branch `3.2.0-prepare` in GitHub, start standalone or cluster to test it. And then you can  add comment in this issue or in mail thread https://lists.apache.org/thread/xgg1qx927t5dnmlq3yy5wjw5sy2b6547

# Check List

## Docs

* [ ] Terraform Deploy

## Major functionality

* [ ] Project
* [ ] Workflow
* [ ] Task type like shell, python, http
* [ ] Datasource like mysql, postgresql, hive

## Refactor functionality

* [ ] Resource center
   * [ ] create resource in folder will in the root dir
   * [ ] delete the old table of resource center
   * [ ] update from task definition and task instance
   * [x] https://github.com/apache/dolphinscheduler/issues/14393
* [ ] Datasource center
   * [x] https://github.com/apache/dolphinscheduler/pull/14381 

## New functionality

* User friendly
    * [ ] UI only: More hyperlinks jump between resource, adjustable column width
    * [ ] Default tenant: Out of box run workflow by default tenant
    * [ ] Run or rerun task in task instance
    * [ ] Human readable json export result
* Cloud native
    * [ ] Kubernetes Real-time log and custom label support
    * [ ] Support KEDA autoscaler worker
    * [ ] Support Terraform deploy to AWS
    * [ ] Multi arch for zookeper and postgresql(all services are supported now)
* Resource center
    * [ ] Refactor resource center, we use provider API to list and manage
resource now
    * [ ] Allow resource re-upload now
* Datasource
    * [ ] New datasource:
snowflake、databend、kyuubi、oceanbase、dameng、azuresql、starrocks、AWS
Athena
    * [ ] Support access key for redshift datasource
* Tasks
    * [ ] New tasks: azure datafactory、apache
linkis、Kubeflow、datasync、remote-shell、AWS Database Migration、Java Task
    * [ ] Improve for exists: Add presto for datax, parameter passing for
python and http, sql task multiple sql delimiter, dependent depend
itself
    * [ ] Introduce task cache for MLops or other long-run tasks
* Parameter
    * [ ] Add new rule of build-in function
    * [ ] Introduce file type parameter
    * [ ] Startup parameters have the highest priority
* [ ] Logs: Introduce remote logs mechanism and support Google Cloud
Storage、S3、OSS up to now
* API:
    * [ ] Introduce some new restful API(experimental), including
taskInstance、workflow state、workflowInstance、workflow and
schedule、task relation
    * [ ] Can get task instance id when triggering workflow via API
    * [ ] Registry: Introduce etcd, jdbc supported
