### ISSUE TITLE
[expired][easy to fix list] good first contributor

### ISSUE THREAD

**Issue by CalvinKirs** [apache/dolphinscheduler#4124]
The following list is the latest newbie tasks (keep up to date). If you are participating in an open source project for the first time, it is recommended to choose one of the following tasks to practice. The first task is used to familiarize yourself with the submission process and feel the friendliness of the community. If you are interested in a task, please leave a message, and then I will assign the task to you. By the way, please submit a PR in 2 weeks 

---
下面是最新的新手任务列表(一直保持更新, 新手贡献者只看我这一条信息就够了)，如果您是第一次参与开源贡献，建议从以下任务列表中选择一个练手，第一个任务用于熟悉提交流程和感受社区友好度。如果您对某个任务感兴趣，请打开这个 issue 链接在其评论区留言，然后我会将该任务分给您，认领后请于 2 周内提交一个 PR,  2 周后没提交 PR 的话，这个新手任务也可以由新伙伴来认领哈! 

TODO list

- [ ] [Improvement][Task] Improved shell task execution result log information #5469

- [ ] [Improvement][job instance]start-time and end-time good first issue volunteer wanted #5621 

- [ ] [Improvement][project management] Modify the title easy to fix good first issue user experience #5622 

- [ ] [Doc] move the Doc of Ambari Integration to official website repository #5608

- [ ] [code][uint test] Improve code test coverage( This is a big feature,  You can create sub-issues for specific sub-issues)

- [ ] [Improvement][Api] Adding transaction when update process definition #5546

- [ ] [Improvement][SQL]SQL optimization( This is a big feature, You can create sub-issues for specific sub-issues) #5061 
 

submit code：https://dolphinscheduler.apache.org/zh-cn/community/development/submit-code.html
pr and code style notice：https://dolphinscheduler.apache.org/zh-cn/community/development/pull-request.html

**Comment by kevinsun2010** [comment]
what is function  this issues ？

> This is a newbie task list. If you are contributing for the first time, it is recommended that you select this task first. You can leave a message in the issue of the task you are interested in, and I will assign the task to you

what is function  this issues ？

**Comment by CalvinKirs** [comment]
todo list

- [ ] [website]docs  Improve the English version of the official community documentation easy to fix #3562 

- [ ] [website]docs  database initialize #3766 

- [ ] [code][Improvement][server] When the tenant does not exist, the task execution should throw an exception

- [ ] [code][Bug][docker] the file requirements.yaml in helm mode has error flag 

- [ ] [code][ui] Change the no to taskinstance, processinstance, processdefinition id UI easy to fix
#3725

**Comment by CalvinKirs** [comment]
> what is function this issues ？
> 
> > This is a newbie task list. If you are contributing for the first time, it is recommended that you select this task first. You can leave a message in the issue of the task you are interested in, and I will assign the task to you
> 
> what is function this issues ？

This is a newbie task list. You can claim the tasks you are interested in

**Comment by dailidong** [comment]
if you have any question about the issues , please leave message
just relax,   please feel free, you can ask any thing about issues

**Comment by AlleriaWindrunner** [comment]
I want to resolve the bug #3237

**Comment by lgcareer** [comment]
@AlleriaWindrunner Hi,You can also give the message on https://github.com/apache/incubator-dolphinscheduler/issues/3237,Then I will assign it to you.

**Comment by aNotBadCoder** [comment]
hi
@CalvinKirs 

The three issues have been closed, show
 * [ ] xx
not
*  [x] xx

> * [ ]  [website]docs  Improve the English version of the official community documentation easy to fix #3562
> * [ ]  [website]docs  database initialize #3766
> * [ ]  [code][UI][Improvement][UI] Add description field to data source list #4326

If there is a new issue ,you can notify me.

**Comment by CalvinKirs** [comment]
> hi
> @CalvinKirs
> 
> The three issues have been closed, show
> 
> * [ ]  xx
>   not
> * [x]  xx
> 
> > * [ ]   [website]docs  Improve the English version of the official community documentation easy to fix #3562
> > * [ ]   [website]docs  database initialize #3766
> > * [ ]   [code][UI][Improvement][UI] Add description field to data source list #4326
> 
> If there is a new issue ,you can notify me.

hi, there is an online demo table in the navigation bar of the official website. We need to remove it. It does not conform to the apache specification. Can you remove it?

**Comment by aNotBadCoder** [comment]
> > hi
> > @CalvinKirs
> > The three issues have been closed, show
> > 
> > * [ ]   xx
> >   not
> > * [x]   xx
> > 
> > > * [ ]    [website]docs  Improve the English version of the official community documentation easy to fix #3562
> > > * [ ]    [website]docs  database initialize #3766
> > > * [ ]    [code][UI][Improvement][UI] Add description field to data source list #4326
> > 
> > 
> > If there is a new issue ,you can notify me.
> 
> hi, there is an online demo table in the navigation bar of the official website. We need to remove it. It does not conform to the apache specification. Can you remove it?

where is address ? I can try it.

**Comment by CalvinKirs** [comment]
> > > hi
> > > @CalvinKirs
> > > The three issues have been closed, show
> > > 
> > > * [ ]    xx
> > >   not
> > > * [x]    xx
> > > 
> > > > * [ ]     [website]docs  Improve the English version of the official community documentation easy to fix #3562
> > > > * [ ]     [website]docs  database initialize #3766
> > > > * [ ]     [code][UI][Improvement][UI] Add description field to data source list #4326
> > > 
> > > 
> > > If there is a new issue ,you can notify me.
> > 
> > 
> > hi, there is an online demo table in the navigation bar of the official website. We need to remove it. It does not conform to the apache specification. Can you remove it?
> 
> where is address ? I can try it.

https://github.com/apache/incubator-dolphinscheduler-website

**Comment by aNotBadCoder** [comment]
> > > > hi
> > > > @CalvinKirs
> > > > The three issues have been closed, show
> > > > 
> > > > * [ ]     xx
> > > >   not
> > > > * [x]     xx
> > > > 
> > > > > * [ ]      [website]docs  Improve the English version of the official community documentation easy to fix #3562
> > > > > * [ ]      [website]docs  database initialize #3766
> > > > > * [ ]      [code][UI][Improvement][UI] Add description field to data source list #4326
> > > > 
> > > > 
> > > > If there is a new issue ,you can notify me.
> > > 
> > > 
> > > hi, there is an online demo table in the navigation bar of the official website. We need to remove it. It does not conform to the apache specification. Can you remove it?
> > 
> > 
> > where is address ? I can try it.
> 
> https://github.com/apache/incubator-dolphinscheduler-website
What do you want remove  ? Can you explain that? Which online demo table?

**Comment by aNotBadCoder** [comment]
@CalvinKirs 
![image](https://user-images.githubusercontent.com/42240041/103605565-2ebbc380-4f4f-11eb-838d-80409f2af8ba.png)
Remove it?

**Comment by aNotBadCoder** [comment]
@CalvinKirs  I can resolve #4380, please assign it to me.

**Comment by dailidong** [comment]
> The following list is the latest newbie tasks (keep up to date). If you are participating in an open source project for the first time, it is recommended to choose one of the following tasks to practice. The first task is used to familiarize yourself with the submission process and feel the friendliness of the community. If you are interested in a task, please leave a message, and then I will assign the task to you
> 
> 下面是最新的新手任务列表(一直保持更新)，如果您是第一次参与开源贡献，建议从以下任务列表中选择一个练手，第一个任务用于熟悉提交流程和感受社区友好度。如果您对某个任务感兴趣，欢迎留言，然后我会将该任务分给你
> 
> TODO list
> 
> * [ ]   [website][doc] low version of Mysql jdbc driver may cause serious problem #4421
> * [ ]   [code]Improvement][API] Reduce the size of returned data for list interfaces #4466
> * [ ]  [Feature][UI] When the process definition is running, the pop-up box can manually set the global parameters. #4423
> * [ ]  [Feature][UI] add an option to the UI page for saving the workflow definition: whether to go online? online by default #4463
> 
> submit code：https://dolphinscheduler.apache.org/zh-cn/docs/development/submit-code.html
> pr and code style notice：https://dolphinscheduler.apache.org/zh-cn/docs/development/pull-request.html

I will remove issue #4463，it has been completed

**Comment by zapjone** [comment]
I want to resolve the bug #4727

**Comment by liuziyingbeidou** [comment]
I want improve test coverage of ProcessService#createCommand

**Comment by CalvinKirs** [comment]
> I want improve test coverage of ProcessService#createCommand

looking forward submit your PR

**Comment by jiang-zilong** [comment]
dophin在使用shell脚本调度的时候，脚本中是占位符传的参数，这要用dophin怎么传呢？ 说了很多方式都没有解决，求解

**Comment by davidzollo** [comment]
this issue has been closed, Please go to the new issue: https://github.com/apache/dolphinscheduler/issues/5689
