### ISSUE TITLE
[Improvement][API] Improvement Swagger API parameter optimization 

### ISSUE THREAD

**Issue by zhuangchong** [apache/dolphinscheduler#4821]
**Describe the question**
Improvement Swagger API parameter optimization 

Have a problem:
*  Incorrect name of Swagger API parameter
* The swagger API parameter is required
*  Missing API interface parameters
, etc.

**Which version of DolphinScheduler:**
 -[1.3.4-release,dev]

**Task**

- [ ] AccessTokenController AlertGroupController AlertPluginInstanceController
- [ ] DataAnalysisController DataSourceController ExecutorController
- [ ] LoggerController LoginController MonitorController
- [ ] ProjectController ProcessDefinitionController ProcessInstanceController
- [ ] QueueController ResourcesController SchedulerController
- [ ] TenantController TaskInstanceController UiPluginController
- [ ] UsersController WorkerGroupController WorkFlowLineageController

- [x] TaskRecordController -Did not call

**Comment by ptyp** [comment]
Hi, in case not to misunderstand your meaning, I want to check do you mean this task is to perfect the API docs including but not limited to exampling the parameter and fix some paramaters? If I understand it correctly, I can handle these tasks. Please assign to me.

**Comment by zhuangchong** [comment]
> Hi, in case not to misunderstand your meaning, I want to check do you mean this task is to perfect the API docs including but not limited to exampling the parameter and fix some paramaters? If I understand it correctly, I can handle these tasks. Please assign to me.

ok，this task is to perfect the API swagger docs
