### ISSUE TITLE
Docker & K8s Improvement Plan

### ISSUE THREAD

**Issue by chengshiwen** [apache/dolphinscheduler#4837]
### 1.3.5-release

Docker Improvement Plan

- [x] Reduce image size
- [x] Remove frontend/nginx
- [x] Remove stdout log in properties
- [x] improve compose/swarm deployment
- [x] Fix random PSQLException
- [x] Sync docker conf templates to the latest conf properties
- [x] Update outdated readme

K8s Improvement Plan

- [x] Remove frontend/nginx
- [x] Remove redundant configs
- [x] Support resource storage when fs.defaultFS=file:///
- [x] Fix task log disappear after recreating or upgrading helm release
- [x] Improve long host display in K8s
- [x] Update outdated readme

### dev & 1.3.6-release

Docker Improvement Plan

- [x] Reduce image size
- [x] Remove frontend/nginx
- [x] Remove stdout log in properties
- [x] improve compose/swarm deployment
- [x] Fix random PSQLException
- [x] Sync docker conf templates to the latest conf properties
- [x] Update outdated readme
- [x] Rename `WORKER_GROUP` to `WORKER_GROUPS` (#4843)
- [x] Add FAQ support about MySQL and Oracle in readme (#4732 #4871)
- [x] Add default login username and password in readme (#4881)
- [x] Check compatibility in Windows (#4804)
- [x] Fix invalid volume specification in Windows (#4886)
- [x] Support supervisor management (#2687)
- [x] Optimize log stdout with supervisor (#4897)
- [x] Fix that can not build a docker image on Windows (#3124)
- [x] Support docker compose file 3.1+ version
- [x] Add tenant tip for quick start
- [x] Sync the latest configs in master.properties and worker.properties
- [x] Support all configs in common.properties
- [x] Improve the environment variables and reduce the duplication configs
- [x] Fix mysql check
- [x] Add config.env.sh for docker compose and swarm
- [x] Add `MASTER_SERVER_OPTS`, `WORKER_SERVER_OPTS`, `ALERT_SERVER_OPTS`, `API_SERVER_OPTS`, `LOGGER_SERVER_OPTS`
- [x] Support skywalking config in docker
- [x] Replace alpine with debian:slim (#5155)
- [x] Remove redundant postgresql-client and mysql-client
- [x] Add faq for python, spark, hadoop, flink and datax
- [x] Add docs for support matrix on docker (#5068)
- [x] Support task scalability on Docker such as Spark, Flink and DataX (#5100)

K8s Improvement Plan

- [x] Remove frontend/nginx
- [x] Remove redundant configs
- [x] Support resource storage when fs.defaultFS=file:///
- [x] Fix task log disappear after recreating or upgrading helm release
- [x] Improve long host display in K8s
- [x] Adapt to the latest alert-server with updated config and port 50052
- [x] Update outdated readme
- [x] Rename `WORKER_GROUP` to `WORKER_GROUPS` (#4843)
- [x] Add FAQ support about MySQL and Oracle in readme (#2584)
- [x] Add FAQ support to use namespace, access ui and delete pv in readme
- [x] Incorrect host problem in minikube (#4905)
- [x] Check compatibility in all Kubernetes 1.12+
- [x] Support local docker image
- [x] Optimize image pull secret
- [x] Optimize fullname
- [x] Optimize metadata name
- [x] Sync the latest configs in master.properties and worker.properties
- [x] Support all configs in common.properties
- [x] Improve the environment variables and reduce the duplication configs
- [x] Support skywalking config in k8s
- [x] Unify annotations, affinity, nodeSelector, tolerations, resources and probe in K8s
- [x] Support more service access like ClusterIP, NodePort and LoadBalancer
- [x] Improve https tip in k8s
- [x] Add `MASTER_SERVER_OPTS`, `WORKER_SERVER_OPTS`, `ALERT_SERVER_OPTS`, `API_SERVER_OPTS`, `LOGGER_SERVER_OPTS`
- [x] Add faq for python, spark, hadoop, flink and datax
- [x] Add docs for support matrix on k8s (#5068)
- [x] Support task scalability on K8s such as Spark, Flink and DataX (#5100)
- [x] Fix quartz cron task cannot take effect in K8s (#5351)
- [x] Reduce long host and improve long host display on K8s

**Comment by chengshiwen** [comment]
@dailidong @chenxingchun

**Comment by xingchun-chen** [comment]
good job

**Comment by davidzollo** [comment]
good job
