### ISSUE TITLE
Docker & K8s Improvement Plan Round 2

### ISSUE THREAD

**Issue by chengshiwen** [apache/dolphinscheduler#5405]
## dev & 1.3.7-release

- [x] [Docker/K8s] Improve the compatibility of python home
- [x] [Docker] Optimize docker-swarm/check script
- [x] [Docker/DB] Update default username and password of database
- [x] [Docker/K8s] Specify version for all images
- [x] [Docker] Optimize PS1 and WORKDIR
- [x] [Docker/K8s] Reduce heap size in `create-dolphinscheduler.sh/upgrade-dolphinscheduler.sh`
- [x] [Bug][K8s] Master and worker cannot get the right address with custom DNS in 1.3.6 #5431
- [x] [Docker/K8s] Unable to receive enterprise wechat alarm normally #5523
- [x] [Docker/K8s] Adapt to registry SPI
- [x] [Docker]Docker image support multi-arch especially in docker-compose #5858

## Related issue

Docker & K8s Improvement Plan Round 1: #4837
