### ISSUE TITLE
[Improvement][ARM64] Improve development and deployment on arch ARM64

### ISSUE THREAD

**Issue by chengshiwen** [apache/dolphinscheduler#5615]
**Describe the question**

In arm64 especially like Apple Silicon chip, there are many problems that cause development and deployment to not work properly:

- [ ] Compile error for dolphinscheduler-ui, node v16+ required #5595
- [ ] JDK support problem for arm64 with Mac M1 Silicon, not yet sure
- [ ] [Bug] Incompatible big sur system with M1 chip #6031
- [x] Docker image arch doesn't support arm64 #5858

**What are the current deficiencies and the benefits of improvement**
- New developer can develop and package DolphinScheduler on arm64 environment
- New user can deploy DolphinScheduler by docker on arm64 environment

**Which version of DolphinScheduler:**
 -[dev]
 -[1.3.x]

**Additional information**
- The BitNami images we currently use include [bitnami/postgresql](https://hub.docker.com/r/bitnami/postgresql) and [bitnami/zookeeper](https://hub.docker.com/r/bitnami/zookeeper). They do not support arm64 architecture and will be released in the future.

**Comment by xied75** [comment]
Hi guys,

I contacted @dailidong yesterday via gmail. Sorry that I didn't go the normal channels like mail-list for wanting a quick answer.

Now by following your exchange of emails I found this issue.

1, May I suggest to change the "Label" from "apple silicon" into "arch-arm64", and if you prefer to also create "arch-arm32", this is in line with other popular projects of how best to name/label the arch/ISA. Besides, "apple silicon" is hardly the typical chip people think of when ARM64 is mentioned. This will make people searching issues easier.

2, Docker Hub does officially support multiple arch as shown here for example: https://hub.docker.com/_/zookeeper, with these listed immediately under the title **IBM Z, x86-64, ARM 64, ARM, 386, PowerPC 64 LE**.

3, Was there a specific reason to use docker images from bitnami rather than Docker official as mentioned above? Or https://hub.docker.com/_/postgres. Both postgres and zookeeper official images already support ARM64.

Would be great to have official ARM64 images soon,

Best regards,

Dong

**Comment by chengshiwen** [comment]
@xied75 Thanks for your feedback.
1, Good suggestion

2 & 3, The reason for using Bitnami's images is that the [Bitnami repository](https://github.com/bitnami/charts) containing PostgreSQL and ZooKeeper is used in K8s. It has richer features, such as standard and unified management and configuration. Therefore, the corresponding images are used in docker compose and swarm. This way reduces maintenance costs. We have considered replacing them with the [official library](https://hub.docker.com/), but the current feedback that the demand for using arm64 is not so strong, and its replacement cost under K8s is relatively high. So in K8s we will keep the Bitnami images until they released the arm64 architecture next. As for docker compose and swarm, before the Bitnami images don't support the arm64 architecture, it is possible to switch to the official library. Anyway, arm64 architecture support will meet soon

**Comment by chengshiwen** [comment]
Now, DolphinScheduler has supported the arm64 arch on dev branch (#5859) and [1.3.7 release](https://github.com/apache/dolphinscheduler/releases/tag/1.3.7).
