### ISSUE TITLE
[easy to fix list] good first contributor

### ISSUE THREAD

**Issue by davidzollo** [apache/dolphinscheduler#5689]
The following list is the latest newbie tasks (keep up to date). If you are participating in an open source project for the first time, it is recommended to choose one of the following tasks to practice. The first task is used to familiarize yourself with the submission process and feel the friendliness of the community. If you are interested in a task, Please leave a message, for example, `I am interested in implementing this task`, please submit a PR in 2 weeks if you leave the message. If more than 2 weeks, other contributors are welcome to do it.

TODO list

- [x] #5485
- [x] #5541
- [x] #5918
- [x] #7351
- [x] #8189
- [ ] #8628
- [x] #8955
- [x] #9322
- [x] #10482
- [ ] 🔥 Documentation
    - [x] #4068
    - [x] #8955
    - [x] #13041
    - [x] #13542 
  - Task Usage, we should add basic usage, example, notice about tasks, track in #6535 
    * [x] #8019
    * [x] #8027
    * [x] #8030
    * [x] #8031
    * [x] #8189
    * [x] #8228
- [x] #10482
- [x] #11279 
- [x] #11537 
- [x] #11801
- [x] #11805
- [x] #11867
- [x] #11906
- [x] #11913
- [x] #11940
- [x] #13596 
- [x] #13810

and more good first issues please refer to [**`Good First Issues`**](https://github.com/apache/dolphinscheduler/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)

Besides these we have listed, you can add some Unit Tests to Improve code test coverage, you can also answer other user's issues or review contributor's PRs, all of these actions are contributions for Apache DolphinScheduler.

submit code：https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/submit-code.md
pr and code style notice：https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md

**Comment by MuzzammilRafiq** [comment]
I want to contribute

**Comment by davidzollo** [comment]
> I want to contribute

good job
 If you are interested in a task, please go to the related issue page, and leave a message in the comment area of this issue

**Comment by nielifeng** [comment]
- [ ] [Feature][unittest] Recover UT in AlertPluginManagerTest.java good first issue new feature #6619
- [ ] [Feature][Dao] Upgrade com.mysql.jdbc.Driver #6505
- [ ] [Improvement][Dependent Node UI] dependent node loaded multiple times #6151
- [ ] [Improvement][Service]Optimize the service module #5949
- [ ] [Improvement][DataSource] all user have all datasource permission,lead data security issues #5897
- [ ] [WebSite][Doc] add release note to download page #5889
- [ ] [Bug][SQL] Suggest to increase the max length of the field resource_ids in the table t_ds_task_definition. #5876
- [ ] [Improvement][Dao UT] Use h2 in UT #5807
- [ ] [Feature][New task node] Loop node that specifies the sleeping time #5791
- [ ] [Improvement][UI experience] Some suggestions for UI experience #5790
- [ ] [Improvement][Code Style] Fix code format #5785
- [ ] [Feature][Docs] Add link to go to the corresponding github address #5745
- [ ] [Improvement][Doc] update the content of the architecture document #5732
- [ ] [Feature][UI] Data source selection drop-down box optimization #5668
- [ ] [Improvement][Api] Adding transaction when update process definition #5546
- [ ] [Feature][SPI] SPI-UI #5541
- [ ] [Improvement][monitor]job monitoring #5485
- [ ] There is a vulnerability in cron.utils 5.0.5 ,upgrade recommended #5293
- [ ] [DOCS][SPI] SPI-DOCS #4068
- [ ] According to folder dependency support?（根据文件夹依赖支持吗） #216

**Comment by davidzollo** [comment]
> * [ ]  [Feature][unittest] Recover UT in AlertPluginManagerTest.java good first issue new feature [[Feature][unittest] Recover UT in AlertPluginManagerTest.java #6619](https://github.com/apache/dolphinscheduler/issues/6619)
> * [ ]  [Feature][Dao] Upgrade com.mysql.jdbc.Driver [[Feature][Dao] Upgrade com.mysql.jdbc.Driver #6505](https://github.com/apache/dolphinscheduler/issues/6505)
> * [ ]  [Improvement][Dependent Node UI] dependent node loaded multiple times [[Improvement][Dependent Node UI] dependent node loaded multiple times #6151](https://github.com/apache/dolphinscheduler/issues/6151)
> * [ ]  [Improvement][Service]Optimize the service module [[Improvement][Service]Optimize the service module #5949](https://github.com/apache/dolphinscheduler/issues/5949)
> * [ ]  [Improvement][DataSource] all user have all datasource permission,lead data security issues [[Improvement][DataSource] all user have all datasource permission,lead data security issues #5897](https://github.com/apache/dolphinscheduler/issues/5897)
> * [ ]  [WebSite][Doc] add release note to download page [[WebSite][Doc] add release note to download page #5889](https://github.com/apache/dolphinscheduler/issues/5889)
> * [ ]  [Bug][SQL] Suggest to increase the max length of the field resource_ids in the table t_ds_task_definition. [[Bug][SQL] Suggest to increase the max length of the field resource_ids  in the table t_ds_task_definition. #5876](https://github.com/apache/dolphinscheduler/issues/5876)
> * [ ]  [Improvement][Dao UT] Use h2 in UT [[Improvement][Dao UT] Use h2 in UT #5807](https://github.com/apache/dolphinscheduler/issues/5807)
> * [ ]  [Feature][New task node] Loop node that specifies the sleeping time [[Feature][New task node] Loop node that specifies the sleeping time #5791](https://github.com/apache/dolphinscheduler/issues/5791)
> * [ ]  [Improvement][UI experience] Some suggestions for UI experience [[Improvement][UI experience] Some suggestions for UI experience #5790](https://github.com/apache/dolphinscheduler/issues/5790)
> * [ ]  [Improvement][Code Style] Fix code format [[Improvement][Code Style] Fix code format #5785](https://github.com/apache/dolphinscheduler/issues/5785)
> * [ ]  [Feature][Docs] Add link to go to the corresponding github address [[Feature][Docs] Add link to go to the corresponding github address #5745](https://github.com/apache/dolphinscheduler/issues/5745)
> * [ ]  [Improvement][Doc] update the content of the architecture document [[Improvement][Doc] update the content of the architecture document  #5732](https://github.com/apache/dolphinscheduler/issues/5732)
> * [ ]  [Feature][UI] Data source selection drop-down box optimization [[Feature][UI] Data source selection drop-down box optimization #5668](https://github.com/apache/dolphinscheduler/issues/5668)
> * [ ]  [Improvement][Api] Adding transaction when update process definition [[Improvement][Api] Adding transaction when update process definition #5546](https://github.com/apache/dolphinscheduler/issues/5546)
> * [ ]  [Feature][SPI] SPI-UI [[Feature][SPI] SPI-UI #5541](https://github.com/apache/dolphinscheduler/issues/5541)
> * [ ]  [Improvement][monitor]job monitoring [[Improvement][monitor]job monitoring #5485](https://github.com/apache/dolphinscheduler/issues/5485)
> * [ ]  There is a vulnerability in cron.utils 5.0.5 ,upgrade recommended [There is a vulnerability in cron.utils 5.0.5 ,upgrade recommended #5293](https://github.com/apache/dolphinscheduler/issues/5293)
> * [ ]  [DOCS][SPI] SPI-DOCS [[DOCS][SPI] SPI-DOCS #4068](https://github.com/apache/dolphinscheduler/issues/4068)
> * [ ]  According to folder dependency support?（根据文件夹依赖支持吗） [According to folder dependency support?（根据文件夹依赖支持吗） #216](https://github.com/apache/dolphinscheduler/issues/216)

good job, the content has updated, thx

**Comment by zhongjiajie** [comment]
Hi @dailidong I found out we have duplicate issue above #6619 and maybe we should remove them.
One more suggestion, maybe we could use issue id directly, instead of copy-paste issue title, for more easy to read.

For example, we should use

* [ ] #6619 

instead of

* [ ] [Feature][unittest] Recover UT in AlertPluginManagerTest.java good first issue new feature. #6619

**Comment by davidzollo** [comment]
> Hi @dailidong I found out we have duplicate issue above #6619 and maybe we should remove them. One more suggestion, maybe we could use issue id directly, instead of copy-paste issue title, for more easy to read.
> 
> For example, we should use
> 
> * [ ]  [[Feature][unittest] Recover UT in AlertPluginManagerTest.java #6619](https://github.com/apache/dolphinscheduler/issues/6619)
> 
> instead of
> 
> * [ ]  [Feature][unittest] Recover UT in AlertPluginManagerTest.java good first issue new feature. [[Feature][unittest] Recover UT in AlertPluginManagerTest.java #6619](https://github.com/apache/dolphinscheduler/issues/6619)

good idea

**Comment by RedemptionC** [comment]
Hi,
In the todo list,#5745 and #5949 has been added twice
And this line has no address attached to it
> [code][uint test] Improve code test coverage( This is a big feature, You can create sub-issues for specific sub-issues)

**Comment by zhongjiajie** [comment]
Hi, here are some `easy to fix` job for python API, could anyone add labels `wanted` or `easy to fix` to them and add them to this issue describute?
https://github.com/apache/dolphinscheduler/issues/6930
https://github.com/apache/dolphinscheduler/issues/6929
https://github.com/apache/dolphinscheduler/issues/6924
https://github.com/apache/dolphinscheduler/issues/6926
https://github.com/apache/dolphinscheduler/issues/6927
https://github.com/apache/dolphinscheduler/issues/6928

**Comment by davidzollo** [comment]
> Hi, here are some `easy to fix` job for python API, could anyone add labels `wanted` or `easy to fix` to them and add them to this issue describute? #6930 #6929 #6924 #6926 #6927 #6928

good job
these issues have been added into the TODO list

**Comment by davidzollo** [comment]
> Hi, In the todo list,#5745 and #5949 has been added twice And this line has no address attached to it
> 
> > [code][uint test] Improve code test coverage( This is a big feature, You can create sub-issues for specific sub-issues)

good job
thanks, I have updated the TODO list

**Comment by jim-parsons** [comment]
I am interested in implementing this task #7227

**Comment by davidzollo** [comment]
> I am interested in implementing this task #7227

I have assigned to you, please submit your PR, thx
if you have any question, please leave a message

**Comment by davidzollo** [comment]
> I want to contribute

hello, Which question are you interested in? I can assign it to you, thx

**Comment by Monesz1** [comment]
I want to contribute. It will be my first time, therefore I'm looking for a beginner issue. :)

**Comment by zhongjiajie** [comment]
> I want to contribute. It will be my first time, therefore I'm looking for a beginner issue. :)

Hi, @Monesz1 all issue in https://github.com/apache/dolphinscheduler/issues/5689#issue-928812038 is good for the first time contributors

**Comment by zhongjiajie** [comment]
remove stale

**Comment by guanboo** [comment]
还有未分派的任务吗？

**Comment by fuchanghai** [comment]
Issues that are not merged can be received

**Comment by zhongjiajie** [comment]
@guanboo for more detail about good first issue you can see in https://github.com/apache/dolphinscheduler/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

**Comment by nitesh-chowdhary** [comment]
With due respect, I would like to have permission for a beginner project to work on. This is my first open source project. I know java as a programming language and can learn things quickly and vividly. So, can I get a chance to be a part of this project.

**Comment by davidzollo** [comment]
> With due respect, I would like to have permission for a beginner project to work on. This is my first open source project. I know java as a programming language and can learn things quickly and vividly. So, can I get a chance to be a part of this project.

of course, you can choose an easy issue to complete it

**Comment by wushanru** [comment]
@davidzollo Is there any unfinished problem suitable for beginners? I can do it

**Comment by zhongjiajie** [comment]
> @davidzollo Is there any unfinished problem suitable for beginners? I can do it

Hi @wushanru , all task in https://github.com/apache/dolphinscheduler/issues/5689#issue-928812038 are unsolved issue, and you can pick one of them to have a try

**Comment by zhongjiajie** [comment]
I propose to abandon this issue and unpin it in our issue due to the new link in https://github.com/apache/dolphinscheduler/pull/14002 I just created, https://github.com/apache/dolphinscheduler/contribute this link maintain by GitHub and all we have to do is add label `good first issue` for the issue, WDYT?

**Comment by davidzollo** [comment]
> I propose to abandon this issue and unpin it in our issue due to the new link in #14002 I just created, https://github.com/apache/dolphinscheduler/contribute this link maintain by GitHub and all we have to do is add label `good first issue` for the issue, WDYT?

I totally agree with what you said.

**Comment by zhongjiajie** [comment]
close due to https://github.com/apache/dolphinscheduler/contribute

**Comment by lnn0418** [comment]
After switching systems and databases, restart the service. The same scheduled task is started hundreds of times at the same time. What is the reason?

**Comment by 614230213** [comment]
3.2.1版本的页面发现2个bug，请问有人修复了吗？1、页面分页查询无法使用；2、数据源编辑页面，什么都不改，直接点确定保存，数据库的密码会被更新为 ******，导致数据源无法使用
