### ISSUE TITLE
[DSIP-1][Feature][Parent] Add Python API for DolphinScheduler

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#6407]
# Description

Add Python API for DolphinScheduler, which allow user define workflow using Python code, aka **workflows-as-code**. And this is parent list to connect all children issues, **until** we public first release to pypi

* [x] mailing-list: https://lists.apache.org/thread.html/rb54aea6cde22d288fb3fefa4b921f155c8237b5bf5b42e4081ba789b%40%3Cdev.dolphinscheduler.apache.org%3E

## Functional

* [x] **First implementation of workflow-as-codes**, including create process definition, tasks, setting tasks relation, run process definition. #6269 
* [x] **How to update workflow**, including task name(would create new task when change task name), task other attribute such as command, relations #6269.
* [x] **Add Missing Parameter**
  * [x] https://github.com/apache/dolphinscheduler/pull/6667
  * [x] https://github.com/apache/dolphinscheduler/pull/6664
* [x] **Add Example How To Use**,
  * [x] Bluck Define, https://github.com/apache/dolphinscheduler/pull/6659
  * [x] Tutorial, https://github.com/apache/dolphinscheduler/pull/6269
* [x] #7539
* 🆘 🆘 🆘 🆘 🆘 **help wanted here**  Support All Task Type 🆘 🆘 🆘 🆘 🆘 
  * [x] 🔥 sub_process #6930
  * [x] 🔥 procedure #6929
  * [x] 🔥 sql #6924
  * [x] 🔥 spark #7346
  * [x] flink #7347
  * [x] MR #7348
  * [x] 🔥 python #6906
  * [x] 🔥 dependent #6926
  * [x] 🔥 http #6906
  * [x] datax #7349
  * [x] 🔥 conditions #6927
  * [x] 🔥 switch #6928

## Dev

* Code style, currently I think we should use [black][black] it better if bot could auto fix it.
  * [x] https://github.com/apache/dolphinscheduler/pull/6679
  * [x] https://github.com/apache/dolphinscheduler/pull/6871
  * [x] https://github.com/apache/dolphinscheduler/pull/6861
* Unit Test.
  * [x] https://github.com/apache/dolphinscheduler/pull/6636
  * [x] Coverage up to 85%, add CI failed if coverage down to 85%, https://github.com/apache/dolphinscheduler/pull/6861
* [x] Add custom
  * [x] exception #6935

## Doc

* [x] Add docs to pyds, currently maybe use [sphinx][sphinx]. #8005

# What we have to consider carefully

1. **A good mechanism to update process definition**: For now DS design base on UI define workflow, which we modify database model step by step, is a quick different from define or update by code. We have to consider who to update it. Cause we should not ask user define process definition code or tasks code in the python API, I currently think maybe we should delete all tasks in process definition and then create new. **It's still could not handle when users change project name and process definition, but we would try to fix it later**
2. **How to combine UI and codes when define and change workflow**: We could update workflow define by UI or by edit Python API code after we create it, and how to combine them. If would cause consistency issues when we create workflow by python api but change them in UI, cause UI modify directly change database metadata but python api do not know and still in the old version. **In python api define way, python file just like template, it parse the code and persist to database**

[sphinx]: https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html
[black]: https://github.com/psf/black

**Comment by zuston** [comment]
@zhongjiajie 

> I'm confused with workflow-as-code, you means it just define the DAG and workflow parameters? Could we combine workflow and user task code(like spark/flink programs)? 

This discussion refers from the Apache email PROPOSAL.

I know that this proposal provides the Python SDK to  build the workflow to run, so it just to make it possible that transform UI operation to workflow-as-code.

But could we combine user-code(like flink-sql or spark program code) with python workflow sdk? This maybe more convenient and easy-understanding.

**Comment by zhongjiajie** [comment]
Hi @zuston, I had answered this question in mailing-list you could see in [this link][1]

> But could we combine user-code(like flink-sql or spark program code) with python workflow sdk? This maybe more convenient and easy-understanding.

Yeah, this is the first step we make, but we wish it could be more powerful. We could support python functional task later, such as

```python
@task
def func_task():
    print('This function could run in DolphinScheduler')

@task
def func_task_follow():
    print('A task run after `func_task` success')

with process_definition('workflow_name') as pd:
    func_task >> func_task_follow
```

Which mean that our python could be run in DolphinScheduler. But I'm not pretty sure could we run pyflink or pyspark code like that cause this need flink and spark environment, but we hope it could.

If you have idea please let me know, or you could join us to build this feature together if you interested in this

[1]: https://lists.apache.org/thread.html/ra4fd314479930ac91efdf6917b9747f3328c8378b6a1a50be2cc6465%40%3Cdev.dolphinscheduler.apache.org%3E

**Comment by zuston** [comment]
Sounds great! @zhongjiajie 

> But I'm not pretty sure could we run pyflink or pyspark code like that cause this need flink and spark environment, but we hope it could.

I'm also not sure but if implemented, it's exciting. I have some other solution to achieve it, but also looking forward DS's proposal.

BTW, I'm glad to join the disscusion on this related proposal.

**Comment by zhongjiajie** [comment]
@zuston Could you share how could you do that? maybe we could follow your step.

> BTW, I'm glad to join the disscusion on this related proposal.

Do you mean you're interested to contribute to DS about python API section?

**Comment by zuston** [comment]
I'm exploring the workflow-as-code architecture based on `ray`, including tenserflow training and spark/flink and so on. 

> Do you mean you're interested to contribute to DS about python API section?

If I have time, I will join it. But Python is not my marjor lang so a little bit difficult

**Comment by zhongjiajie** [comment]
> If I have time, I will join it. But Python is not my marjor lang so a little bit difficult

Sound great, we would add new issue labeled `python` or contain `python`. You could join if you have time 👍

**Comment by zhongjiajie** [comment]
Thanks Calvin add label `DSIP` to this issue.

**Comment by zhongjiajie** [comment]
I would close this issue and end DSIP-1 lifecycle today, any task still WIP would separate into the independent issue.

**Comment by zhongjiajie** [comment]
Close this issue due to https://lists.apache.org/thread/l3jm4qs7czccx1c041jzj3hjcw4nhlg4 is closed
