### ISSUE TITLE
[Feature][Server] Support custom timezone

### ISSUE THREAD

**Issue by caishunfeng** [apache/dolphinscheduler#8310]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

- Unified config timezone by spring
Now DS use the default timezone `GMT+8`, and add the `@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")` on date type field in many object, which is hard to unified timezone and change it.

- Support custom timeone
The api interface return datetime is string type, which lose the timezone info, the same  for api requests, so maybe it should supply customize timezone for user.
    - After discussion, we think it's better to add timezone into user info config, and user can select other timezone freely. If no timezone is specified, default use timezone `UTC +0:00`.
    - UI support user to change timezone, default local timezone.
    - Handler timezone  unified in server

### Task List

  - [x] #8385 
  - [x] #8386
  - [x] #8479
  - [x] #8530

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jim-parsons** [comment]
I think timezone is a non-hign-frequency property and it belongs application level so its not that necessary to customize it.
I check the code and some module like `dolphinscheduler-api` has the spring.jackson-timezone config.

**Comment by caishunfeng** [comment]
> I think timezone is a non-hign-frequency property and it belongs application level so its not that necessary to customize it. 

Now DS use GTM+8 as default and it's hard to use in other countries, so it's a very important feature for development in other countries.

> I check the code and some module like `dolphinscheduler-api` has the spring.jackson-timezone config.

Yes, and the json format annotation should be remove, unified timezone by spring config.

**Comment by jim-parsons** [comment]
> > I think timezone is a non-hign-frequency property and it belongs application level so its not that necessary to customize it.
> 
> Now DS use GTM+8 as default and it's hard to use in other countries, so it's a very important feature for development in other countries.
> 
> > I check the code and some module like `dolphinscheduler-api` has the spring.jackson-timezone config.
> 
> Yes, and the json format annotation should be remove, unified timezone by spring config.

got it. if the `spring config` solution is ok , assign it to me, thx~

**Comment by caishunfeng** [comment]
Hi @tangchunbo I had split the sub issue. If you are interested in, please tell me, thx~

**Comment by jim-parsons** [comment]
> Hi @tangchunbo I had split the sub issue. If you are interested in, please tell me, thx~

ok, i‘ll do this issue. but i've got a question, how do l understand issue #8386 , add timezone into table `t_ds_user`  ? plz help me out

**Comment by caishunfeng** [comment]
> ok, i‘ll do this issue. but i've got a question, how do l understand issue #8386 , add timezone into table `t_ds_user` ? plz help me out
yes, add timezone field into table t_ds_user, and provides an interface to update timezone separately. what do you think? @tangchunbo

**Comment by jim-parsons** [comment]
ok, i'll do the these issues's(#8385 , #8386 ) backend work.
