### ISSUE TITLE
[Feature][e2e] Migrate all exists e2e to ui-next

### ISSUE THREAD

**Issue by zhongjiajie** [apache/dolphinscheduler#8858]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We are plan to release a new front-end components in the next release, which you could see more detail in https://lists.apache.org/thread/8ozcd4n4fjnp93tznfvlw9bp2g6fkryw. But all our existing e2e tests is for the old front-end components. So we have to migrate all existing e2e tests into the new one.

You could find all existing e2e tests in https://github.com/apache/dolphinscheduler/tree/dev/dolphinscheduler-e2e/dolphinscheduler-e2e-case/src/test/java/org/apache/dolphinscheduler/e2e/cases

### DataSource

* [x] ClickhouseDataSourceE2ETest
* [x] HiveDataSourceE2ETest
* [x] MysqlDataSourceE2ETest
* [x] PostgresDataSourceE2ETest
* [x] SqlServerDataSourceE2ETest

### Security

* [x] EnvironmentE2ETest
* [x] TenantE2ETest
* [x] QueueE2ETest
* [x] TokenE2ETest
* [x] UserE2ETest
* [x] WorkerGroupE2ETest

### Project

* [x] ProjectE2ETest    https://github.com/apache/dolphinscheduler/issues/8850.
* [x] WorkflowE2ETest https://github.com/apache/dolphinscheduler/issues/8850.

### Tasks

* [ ] WorkflowSwitchE2ETest https://github.com/apache/dolphinscheduler/issues/8850.

### Resource

* [x] FileManageE2ETest
* [x] FunctionManageE2ETest
* [x] UdfManageE2ETest

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhongjiajie** [comment]
If anyone who interested in this, please comment on this issue and I will assign you subtask to you. 🎉

**Comment by zhongjiajie** [comment]
Hi @SbloodyS , I find out you are working on the related issue. Is there any task you've done above? If there are some sub task already done, please comment on the issue and I would update it

**Comment by zhongjiajie** [comment]
If you are interested in writing new e2e tests, you could find more subtasks in https://github.com/apache/dolphinscheduler/issues?q=is%3Aissue+is%3Aopen+label%3Ae2e+label%3A%22help+wanted%22+cases+in%3Atitle+

**Comment by SbloodyS** [comment]
> Hi @SbloodyS , I find out you are working on the related issue. Is there any task you've done above? If there are some sub task already done, please comment on the issue and I would update it

So far, only ```projecte2etest``` and ```WorkflowE2ETest``` and ```WorkflowSwitchE2ETest``` is unfinished. I'm working on it in #8850.

The rest is merged into ```dev``` branch. Related issue: #8844 #8823 #8727

**Comment by zhongjiajie** [comment]
> > Hi @SbloodyS , I find out you are working on the related issue. Is there any task you've done above? If there are some sub task already done, please comment on the issue and I would update it
> 
> So far, only `projecte2etest` and `WorkflowE2ETest` and `WorkflowSwitchE2ETest` is unfinished. I'm working on it in #8850.
> 
> The rest is merged into `dev` branch. Related issue: #8844 #8823 #8727

Well, that so fast! @SbloodyS

**Comment by SbloodyS** [comment]
Hi @zhongjiajie , ```projecte2etest``` and ```WorkflowE2ETest``` has been finished in #8850. I'll continue working on ```WorkflowSwitchE2ETest``` in a few days later.

**Comment by zhongjiajie** [comment]
I had update the description

**Comment by zhongjiajie** [comment]
@SbloodyS Does it all done and could we close this issue now?

**Comment by SbloodyS** [comment]
> @SbloodyS Does it all done and could we close this issue now?

Yes. I will close it.
